import os
import html
from datetime import datetime
from io import BytesIO
from tools.fetch_tool import fetch_page
from tools.analyze_tool import analyze_page

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, Preformatted, KeepTogether
)
from reportlab.pdfgen import canvas


MODEL_ID = "gemini-1.5-flash-latest"

# ---------------- APPROVAL NODE ----------------
def approval_node(violations: list[dict]) -> dict:
    approved_fixes = []
    rejected_fixes = []

    print("\n" + "="*50)
    print("APPROVAL REVIEW")
    print("="*50 + "\n")

    for i, violation in enumerate(violations, 1):
        print(f"[{i}] {violation['type'].upper()}")
        print(f"    Severity: {violation['severity']}")
        print(f"    Suggestion: {violation['suggestion']}")
        print(f"    Element: {violation['element'][:100]}...")

        response = "y"

        if response.lower() == 'y':
            approved_fixes.append(violation)
            print("    ✓ APPROVED\n")
        else:
            rejected_fixes.append(violation)
            print("    ✗ REJECTED\n")

    return {
        'approved': approved_fixes,
        'rejected': rejected_fixes,
        'total_approved': len(approved_fixes)
    }

# ---------------- FIX NODE ----------------
def fix_node(approved_violations: list[dict]) -> list[dict]:
    fixes = []

    print("\n" + "="*50)
    print("GENERATING FIXES (MOCKED)")
    print("="*50 + "\n")

    mock_fixes = {
        'missing_meta_description': '<meta name="description" content="Example Domain - A demonstration website">',
        'missing_alt_text': '<img src="image.jpg" alt="Descriptive image text">',
        'empty_h1': '<h1>Example Domain</h1>',
        'missing_h1': '<h1>Page Title</h1>',
        'poor_anchor_text': '<a href="/about">About Us</a>',
        'missing_lang_attribute': '<html lang="en">',
        'potential_contrast_issue': '/* Improved contrast: #000 on #fff */'
    }

    for violation in approved_violations:
        vtype = violation['type']
        fixed = mock_fixes.get(vtype, f"<!-- Fixed: {vtype} -->")

        fixes.append({
            'type': vtype,
            'original': violation['element'],
            'fixed': fixed,
            'severity': violation['severity']
        })

        print(f"[{len(fixes)}] {vtype}")
        print(f"    ✓ Mock fix generated\n")

    return fixes

# ---------------- EVALUATE NODE ----------------
def evaluate_node(violations: list[dict], fixes: list[dict]) -> dict:
    total_violations = len(violations)
    fixes_generated = len(fixes)

    if total_violations == 0:
        score = 100.0
    else:
        score = (fixes_generated / total_violations) * 100

    return {
        'score_before': 100 - (total_violations * 10),
        'score_after': 100 - ((total_violations - fixes_generated) * 10),
        'total_issues': total_violations,
        'issues_fixed': fixes_generated,
        'compliance_percentage': score
    }

# ---------------- MARKDOWN REPORT (kept for reference/download option) ----------------
def report_node(url: str, violations: list[dict], fixes: list[dict], evaluation: dict) -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = f"""# Site Doctor Accessibility Audit Report

**Date:** {timestamp}
**URL Scanned:** {url}

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Issues Found | {evaluation['total_issues']} |
| Issues Fixed | {evaluation['issues_fixed']} |
| Compliance Score Before | {evaluation['score_before']}/100 |
| Compliance Score After | {evaluation['score_after']}/100 |
| Improvement | +{evaluation['compliance_percentage']:.1f}% |

---

## Issues Found

"""
    if violations:
        for i, violation in enumerate(violations, 1):
            report += f"""### {i}. {violation['type'].replace('_', ' ').title()}

- **Severity:** {violation['severity'].upper()}
- **Issue:** {violation['suggestion']}
- **Current Element:**
```html
{violation['element']}
```

"""
    else:
        report += "✓ No accessibility issues found!\n\n"

    report += "---\n\n## Recommended Fixes\n\n"

    if fixes:
        for i, fix in enumerate(fixes, 1):
            report += f"""### Fix {i}: {fix['type'].replace('_', ' ').title()}

**Before:**
```html
{fix['original']}
```

**After:**
```html
{fix['fixed']}
```

"""
    else:
        report += "No fixes generated.\n\n"

    report += """---

## Compliance Notes

- Automated scanning detected common accessibility violations
- All fixes require human review before deployment
- Additional manual testing recommended for full WCAG compliance
- Color contrast issues require manual assessment

*Generated by Site Doctor AI Agent*
"""
    return report

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#718096"))
        
        # Footer text
        footer_text = "Generated by Site Doctor AI Agent"
        self.drawString(0.6 * inch, 0.4 * inch, footer_text)
        
        # Page number text
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(letter[0] - 0.6 * inch, 0.4 * inch, page_text)
        
        # Horizontal line above footer
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(0.6 * inch, 0.55 * inch, letter[0] - 0.6 * inch, 0.55 * inch)
        self.restoreState()

def wrap_code_text(text: str, max_chars: int = 80) -> str:
    lines = []
    for line in text.splitlines():
        if len(line) <= max_chars:
            lines.append(line)
        else:
            for i in range(0, len(line), max_chars):
                lines.append(line[i:i+max_chars])
    return "\n".join(lines)

def make_severity_badge(severity: str):
    sev = severity.upper()
    if sev == "HIGH":
        bg = colors.HexColor("#FEE2E2")
        fg = colors.HexColor("#991B1B")
    elif sev == "MEDIUM":
        bg = colors.HexColor("#FFEDD5")
        fg = colors.HexColor("#9A3412")
    else:
        bg = colors.HexColor("#DCFCE7")
        fg = colors.HexColor("#166534")
        
    badge_style = ParagraphStyle(
        'BadgeStyle',
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        textColor=fg,
        alignment=1
    )
    t = Table([[Paragraph(sev, badge_style)]], colWidths=[0.8 * inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), bg),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('BOX', (0, 0), (-1, -1), 1, fg),
    ]))
    return t

def make_code_block(code_text: str, width_pt: float) -> Table:
    escaped = html.escape(code_text)
    wrapped = wrap_code_text(escaped, max_chars=85)
    
    code_style = ParagraphStyle(
        'CodeStyle',
        fontName='Courier',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#2D3748")
    )
    
    p = Preformatted(wrapped, code_style)
    t = Table([[p]], colWidths=[width_pt])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    return t

# ---------------- PDF REPORT (NEW) ----------------
def generate_pdf_report(url: str, violations: list[dict], fixes: list[dict], evaluation: dict) -> bytes:
    """Generate a professional PDF report and return it as bytes."""
    buffer = BytesIO()
    
    margin = 0.6 * inch
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        topMargin=margin, bottomMargin=margin,
        leftMargin=margin, rightMargin=margin
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'DocTitle', parent=styles['Title'],
        fontName='Helvetica-Bold', fontSize=24, leading=28,
        textColor=colors.HexColor('#1A365D'), alignment=0
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle', parent=styles['Normal'],
        fontName='Helvetica-Bold', fontSize=10, leading=14,
        textColor=colors.HexColor('#4A5568')
    )
    meta_label_style = ParagraphStyle(
        'MetaLabel', parent=styles['Normal'],
        fontName='Helvetica-Bold', fontSize=8, leading=11,
        textColor=colors.HexColor('#4A5568')
    )
    meta_val_style = ParagraphStyle(
        'MetaValue', parent=styles['Normal'],
        fontName='Helvetica', fontSize=8, leading=11,
        textColor=colors.HexColor('#718096')
    )
    h2_style = ParagraphStyle(
        'Heading2_Custom', parent=styles['Heading2'],
        fontName='Helvetica-Bold', fontSize=14, leading=18,
        textColor=colors.HexColor('#1A365D'), spaceBefore=18, spaceAfter=8,
        keepWithNext=True
    )
    issue_title_style = ParagraphStyle(
        'IssueTitle', parent=styles['Normal'],
        fontName='Helvetica-Bold', fontSize=11, leading=14,
        textColor=colors.HexColor('#2D3748')
    )
    body_style = ParagraphStyle(
        'Body_Custom', parent=styles['Normal'],
        fontName='Helvetica', fontSize=9, leading=13,
        textColor=colors.HexColor('#2D3748')
    )

    story = []
    
    # Left side: Title & Subtitle
    left_flowables = [
        Paragraph("SITE DOCTOR", title_style),
        Spacer(1, 4),
        Paragraph("AI-Powered Website Accessibility & SEO Audit", subtitle_style)
    ]
    
    # Right side: Metadata
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    right_table_data = [
        [Paragraph("Audit Date:", meta_label_style), Paragraph(timestamp, meta_val_style)],
        [Paragraph("URL:", meta_label_style), Paragraph(url, meta_val_style)]
    ]
    right_table = Table(right_table_data, colWidths=[0.7 * inch, 2.2 * inch])
    right_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]))
    
    header_table = Table([[left_flowables, right_table]], colWidths=[4.4 * inch, 2.9 * inch])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#CBD5E1"), thickness=1, spaceAfter=15))

    # Executive Summary Card Table
    story.append(Paragraph("Executive Summary", h2_style))
    
    metric_title_style = ParagraphStyle(
        'MetricTitle', parent=styles['Normal'],
        fontName='Helvetica-Bold', fontSize=7, leading=9,
        textColor=colors.HexColor('#718096'), alignment=1
    )
    metric_value_style = ParagraphStyle(
        'MetricValue', parent=styles['Normal'],
        fontName='Helvetica-Bold', fontSize=14, leading=18,
        textColor=colors.HexColor('#1A365D'), alignment=1
    )
    
    summary_data = [
        [
            [Paragraph("TOTAL ISSUES", metric_title_style), Spacer(1, 4), Paragraph(str(evaluation['total_issues']), metric_value_style)],
            [Paragraph("ISSUES FIXED", metric_title_style), Spacer(1, 4), Paragraph(str(evaluation['issues_fixed']), metric_value_style)],
            [Paragraph("SCORE BEFORE", metric_title_style), Spacer(1, 4), Paragraph(f"{evaluation['score_before']}/100", metric_value_style)],
            [Paragraph("SCORE AFTER", metric_title_style), Spacer(1, 4), Paragraph(f"{evaluation['score_after']}/100", metric_value_style)],
            [Paragraph("IMPROVEMENT", metric_title_style), Spacer(1, 4), Paragraph(f"+{evaluation['compliance_percentage']:.1f}%", metric_value_style)]
        ]
    ]
    
    summary_table = Table(summary_data, colWidths=[1.46 * inch] * 5)
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#E2E8F0')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 15))

    # Issues Section
    story.append(Paragraph("Issues Found", h2_style))
    if violations:
        for i, v in enumerate(violations, 1):
            title = v['type'].replace('_', ' ').title()
            
            # Inner card flowables
            card_content = []
            
            # Header with title & badge
            header_t = Table([
                [Paragraph(f"Issue #{i}: {title}", issue_title_style), make_severity_badge(v['severity'])]
            ], colWidths=[5.4 * inch, 1.3 * inch])
            header_t.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (-1, -1), 0),
                ('RIGHTPADDING', (0, 0), (-1, -1), 0),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ]))
            card_content.append(header_t)
            card_content.append(Paragraph(f"<b>Description:</b> {v['suggestion']}", body_style))
            card_content.append(Spacer(1, 6))
            card_content.append(Paragraph("<b>Current HTML Element:</b>", body_style))
            card_content.append(Spacer(1, 4))
            card_content.append(make_code_block(v['element'], 501.6))
            
            # Card table container
            card_table = Table([[card_content]], colWidths=[7.3 * inch])
            card_table.setStyle(TableStyle([
                ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#E2E8F0')),
                ('BACKGROUND', (0, 0), (-1, -1), colors.white),
                ('TOPPADDING', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                ('LEFTPADDING', (0, 0), (-1, -1), 12),
                ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ]))
            
            story.append(KeepTogether([card_table, Spacer(1, 10)]))
    else:
        story.append(Paragraph("No accessibility issues found.", body_style))
        story.append(Spacer(1, 10))

    # Recommended Fixes Section
    story.append(Paragraph("Recommended Fixes", h2_style))
    if fixes:
        for i, fix in enumerate(fixes, 1):
            title = fix['type'].replace('_', ' ').title()
            
            card_content = []
            header_t = Table([
                [Paragraph(f"Fix #{i}: {title}", issue_title_style), '']
            ], colWidths=[5.4 * inch, 1.3 * inch])
            header_t.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (-1, -1), 0),
                ('RIGHTPADDING', (0, 0), (-1, -1), 0),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ]))
            card_content.append(header_t)
            
            card_content.append(Paragraph("<b>Before:</b>", body_style))
            card_content.append(Spacer(1, 4))
            card_content.append(make_code_block(fix['original'], 501.6))
            card_content.append(Spacer(1, 6))
            
            card_content.append(Paragraph("<b>After:</b>", body_style))
            card_content.append(Spacer(1, 4))
            card_content.append(make_code_block(fix['fixed'], 501.6))
            
            card_table = Table([[card_content]], colWidths=[7.3 * inch])
            card_table.setStyle(TableStyle([
                ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#E2E8F0')),
                ('BACKGROUND', (0, 0), (-1, -1), colors.white),
                ('TOPPADDING', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                ('LEFTPADDING', (0, 0), (-1, -1), 12),
                ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ]))
            
            story.append(KeepTogether([card_table, Spacer(1, 10)]))
    else:
        story.append(Paragraph("No fixes generated.", body_style))
        story.append(Spacer(1, 10))

    # Compliance Notes
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#CBD5E1"), thickness=0.5, spaceAfter=15))
    story.append(Paragraph("Compliance Notes", h2_style))
    notes = [
        "Automated scanning detected common accessibility violations.",
        "All fixes require human review before deployment.",
        "Additional manual testing recommended for full WCAG compliance.",
        "Color contrast issues require manual assessment."
    ]
    for note in notes:
        story.append(Paragraph(f"• {note}", body_style))
        story.append(Spacer(1, 3))

    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.read()

# ---------------- MAIN AGENT RUNNER ----------------
def run_agent(url: str):
    print(f"[1] Fetching {url}...")
    html = fetch_page(url)

    print("[2] Analyzing violations...")
    violations = analyze_page(html)

    print("[3] Classifying violations...")
    auto_fixable = [v for v in violations if v['auto_fixable']]
    needs_approval = [v for v in violations if not v['auto_fixable']]

    print("[4] Human approval review...")
    approval_result = approval_node(auto_fixable + needs_approval)

    print("[5] Generating fixes...")
    fixes = fix_node(approval_result['approved'])

    print("[6] Evaluating compliance...")
    evaluation = evaluate_node(violations, fixes)

    print("[7] Generating report...")
    markdown_report = report_node(url, violations, fixes, evaluation)
    pdf_bytes = generate_pdf_report(url, violations, fixes, evaluation)

    print("="*50)
    print(f"WORKFLOW COMPLETE")
    print("="*50)
    print(f"Total violations found: {len(violations)}")
    print(f"Approved for fixing: {len(approval_result['approved'])}")
    print(f"Fixes generated: {len(fixes)}")
    print(f"Compliance Score: {evaluation['score_after']}/100")
    print("="*50 + "\n")

    with open("site_doctor_report.md", 'w', encoding='utf-8') as f:
        f.write(markdown_report)

    with open("site_doctor_report.pdf", 'wb') as f:
        f.write(pdf_bytes)

    print("✓ Report saved to: site_doctor_report.md and site_doctor_report.pdf\n")

    return {
        'violations': violations,
        'approval': approval_result,
        'fixes': fixes,
        'evaluation': evaluation,
        'report': markdown_report,
        'pdf_bytes': pdf_bytes
    }

if __name__ == "__main__":
    result = run_agent("https://bbc.com")